# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db93cc8deec65892f27f3281623f34abbfbb5fbe686e83dc4a842a25a1104e487ad8fecada66c6a19e6210606c6bbe576090c564b3589e9449eac5886fad146f

test:
  secret_key_base: 1697c47e8c24f77036118e906dc72266e7744f28dd908c390b07563fb2bac7281878e306a228eb6ff1db776c230df6e11dbb4edec1272eff2789ef256bc85540

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
